### 201 {}

POST http://localhost:5000/api/auth/signup
Content-Type: application/json

{
  "name": "Testtt",
  "email": "t@1247863t.com",
  "password": "1111",
  "role": "user"
}

### 200 {}

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "garbiche.bucket90@gmail.com",
  "password": "11"
}