### 201 {}

POST http://localhost:5000/api/upload
Content-Type: application/json

{
  "title": "Sample Title",
  "author": "John Doe",
  "fileName": "/images/gallery/1724541511112.png"
}


### 200 {}

GET http://localhost:5000/api/upload


### 204 {}

DELETE http://localhost:5000/api/upload/1

### 200 {}
PATCH http://localhost:5000/api/upload/2
Content-Type: application/json

{
  "title": "Sample Titledddddd",
  "author": "John Doedddd",
  "fileName": "/images/gallery/1724546735292.png"
}
