### 201 {}

POST http://localhost:5000/api/upload
Content-Type: application/json

{
  "title": "Sample Title",
  "author": "John Doe",
  "fileName": "1724002609840.png"
}


### 200 {}

GET http://localhost:5000/api/upload
